name: dispatch

on: [repository_dispatch]

jobs:
  manual_deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: respository dispatch testing
        if: github.event.action == 'dkube'
        env:
          DISPATCH_PAYLOAD: ${{ toJson(github.event) }} 
        run: |
             echo "$DISPATCH_PAYLOAD"
