name: Docker Image CI

on: [deployment]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: 
          docker build . --file ./logs/logstash/logstash_7.0.1/Dockerfile --tag ocdr/dkube-logstash:jafar;
          sudo docker push ocdr/dkube-logstash:jafar
