name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: 
          docker build . --file ./logs/logstash/logstash_7.0.1/Dockerfile --tag ocdr/dkube-logstash:jafar
