name: CI

on: [deployment]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
        DEPLOYMENT_CONTEXT: ${{ toJson(github.event) }} 
      run: |
             echo "$DEPLOYMENT_CONTEXT"
