name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
